### ISSUE TITLE
且看最后一步的灵异事件

### ISSUE THREAD

**Issue by zhangshenhua** [picasso250/js-go#2]
10,15 1
6,2 2
4,1 1
11,1 2
10,4 1
4,3 2
13,2 1
8,4 2
6,10 1
13,10 2
10,7 1
3,10 2
10,11 1
13,13 2
2,13 1
4,14 2
1,13 1
4,13 2
5,14 1
3,12 2
1,12 1
1,11 2
2,15 1
11,7 2
1,15 1
6,13 2
2,16 1
5,13 2
2,14 1
6,14 2
3,15 1
5,15 2
4,15 1
5,16 2
4,16 1
5,17 2
4,17 1
1,17 2
0,16 1
1,16 2
2,17 1
0,17 2
1,18 1
2,18 2
0,14 1
0,13 2
0,15 1
0,18 2
3,17 1
3,18 2
4,18 1

12,3 1
14,3 2
14,16 1
15,15 2
1,18 1
1,17 2
1,16 1
0,17 2
0,18 1
2,18 2
3,18 1
3,14 2
2,18 1
5,18 2
3,16 1
2,12 2
1,14 1

15,7 1
0,11 2
1,17 1
0,17 2
4,12 2
3,13 1
0,17 2
0,16 1
1,16 2
2,16 1
3,16 2
4,16 1
1,17 2
2,17 1
3,17 2
4,17 1
0,18 2

0,12 1
1,16 2
0,17 1
16,12 2
1,16 1
8,13 2
0,13 1
6,18 2
1,17 1
6,16 2
0,18 1

3,16 2  #出错了

**Comment by picasso250** [comment]
fix

**Comment by zhangshenhua** [comment]
reopen it！

提子的子也被一起提掉了
