### ISSUE TITLE
这个bug厉害

### ISSUE THREAD

**Issue by zhangshenhua** [picasso250/js-go#3]
![image](https://user-images.githubusercontent.com/998083/90246895-1942e180-de68-11ea-91bc-0e61bd986094.png)

1,17 1
1,18 2
2,17 1
1,16 2
0,16 1
0,17 2
1,15 1
0,15 2
2,16 1
0,14 2
1,14 1
0,13 2
0,12 1
1,13 2
2,14 1
2,13 2
2,15 1
2,18 2
3,18 1
3,17 2
0,18 1
0,16 2
1,18 1
3,14 2
3,15 1
4,15 2
3,16 1
4,16 2
2,18 1
4,18 2
1,17 1
1,18 2
2,18 1
2,17 2
2,16 1
1,17 2
3,18 1
1,15 2
3,16 1
2,15 2
3,15 1
1,14 2
1,12 1
2,14 2
2,12 1
2,18 2
3,13 1
0,18 2
4,14 1
3,16 2
5,15 1
3,15 2
5,16 1
2,16 2
4,17 1
3,18 2
5,18 1
1,17 2
2,17 1
3,17 2
0,16 1
1,16 2
2,16 1
3,16 2
4,16 1
0,15 2
1,15 1
2,15 2
3,15 1
3,14 2
2,14 1
1,14 2
5,17 1
2,15 2
1,15 1
2,15 2
1,15 1
2,15 2
1,15 1
2,18 2
0,14 1
2,15 2
2,16 1
2,13 2
0,15 1
0,13 2
0,17 1
0,18 2
2,17 1
2,15 2
1,13 1
3,14 2
4,18 2
3,18 1
4,18 2
3,18 1
4,18 2
2,17 1
0,17 2
3,18 1
1,18 2
0,15 1
1,15 2
2,16 1
3,16 2
3,17 1
0,16 2
3,14 1
0,14 2
0,15 1
1,15 2
1,16 1
1,17 2
0,17 1
0,16 2
0,14 2
1,14 1

0,15 1
0,16 2
0,13 1
0,15 2
2,15 1
0,15 2
0,14 1
1,15 2
0,16 1
0,15 2
1,15 1
1,18 2
0,15 1
0,18 2
2,18 1
1,17 2
1,18 1
0,11 2
0,18 1
1,11 2
2,13 1
1,17 2
2,11 2
3,16 1
3,12 2

**Comment by picasso250** [comment]
倒第4行的 1,17 2 是怎么出来的啊？我现在看是禁手啊

**Comment by zhangshenhua** [comment]
reopen it!

这张谱复现成这样是错的。
