### ISSUE TITLE
气未尽而提，还不提干净

### ISSUE THREAD

**Issue by zhangshenhua** [picasso250/js-go#4]
1,17 1
1,18 2
2,17 1
1,16 2
0,16 1
0,17 2
1,15 1
0,15 2
2,16 1
0,14 2
1,14 1
0,13 2
0,12 1
1,13 2
2,14 1
2,13 2
2,15 1
2,18 2
3,18 1
3,17 2
0,18 1
0,16 2
1,18 1
3,14 2
3,15 1
4,15 2
3,16 1
4,16 2
2,18 1
4,18 2
1,17 1
1,18 2
2,18 1
2,17 2
2,16 1
1,17 2
3,18 1
1,15 2
3,16 1
2,15 2
3,15 1
1,14 2
1,12 1
2,14 2
2,12 1
2,18 2
3,13 1
0,18 2
4,14 1
3,16 2
5,15 1
3,15 2
5,16 1
2,16 2
4,17 1
3,18 2
5,18 1
1,17 2
2,17 1
3,17 2
0,16 1
1,16 2
2,16 1
3,16 2
4,16 1
0,15 2
1,15 1
2,15 2
3,15 1
3,14 2
2,14 1
1,14 2
5,17 1
2,15 2
1,15 1
2,15 2
1,15 1
2,15 2
1,15 1
2,18 2
0,14 1
2,15 2
2,16 1
2,13 2
0,15 1
0,13 2
0,17 1
0,18 2
2,17 1
2,15 2
1,13 1
3,14 2
4,18 2
3,18 1
4,18 2
3,18 1
4,18 2
2,17 1
0,17 2
3,18 1
1,18 2
0,15 1
1,15 2
2,16 1
3,16 2
3,17 1
0,16 2
3,14 1
0,14 2
0,15 1
1,15 2
1,16 1
1,17 2
0,17 1
0,16 2
0,14 2
1,14 1

0,15 1
0,16 2
0,13 1
0,15 2
2,15 1
0,15 2
0,14 1
1,15 2
0,16 1
0,15 2
1,15 1
1,18 2
0,15 1
0,18 2
2,18 1
1,17 2
1,18 1
0,11 2
0,18 1
1,11 2
2,13 1
1,17 2
2,11 2
3,16 1
3,12 2
5,14 1
4,15 2
10,12 2
16,14 1
4,13 2
8,9 1
5,13 2
9,14 1
6,14 2
11,17 1
4,15 2
6,15 2
4,15 1
6,16 2
4,18 1
6,17 2
9,17 1
6,18 2
1,16 1
8,12 2
2,17 1
5,12 2
1,18 1
4,10 2
0,17 1
1,17 2
2,18 2
3,16 1
3,18 2
3,17 1
4,17 2
4,18 1
1,15 2
1,14 1
2,15 2
2,14 1
2,16 2
3,15 1
0,15 2
0,14 1
0,16 2
2,15 1
0,15 2
1,13 1
1,15 2
3,14 1
4,16 2
4,15 1
5,16 2
5,15 1
5,17 2
3,18 1
2,18 2
3,13 2
2,18 1
0,16 2
1,17 1
0,16 2
2,16 1
0,15 2
1,15 1
0,15 2
0,16 1
0,13 2
0,15 1
1,12 2
2,13 1
2,12 2
4,14 1

5,14 2 #错

**Comment by picasso250** [comment]
0,15 1 那一步是怎么回事呢？

**Comment by picasso250** [comment]
是因为之前的程序有问题，可以生成非法棋谱。
